# Generated by Django 3.0.5 on 2020-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('text_color', models.CharField(choices=[('red', 'red'), ('white', 'white'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('yellow', 'yellow')], default='black', max_length=100)),
                ('background_color', models.CharField(choices=[('red', 'red'), ('white', 'white'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('yellow', 'yellow'), ('black', 'black')], default='white', max_length=100)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
